# Generated by Django 4.1.13 on 2024-10-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('IdDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('NombreDepartamento', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('IdEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEmpleado', models.CharField(max_length=500)),
                ('Departamento', models.CharField(max_length=500)),
                ('FechaDeIngreso', models.DateField()),
                ('NombreArchivoFoto', models.CharField(max_length=500)),
            ],
        ),
    ]
